export const initialProducts =  [
    {
        "id": "1",
        "title": "Nike Shoes 01",
        "image": 'https://content2.rozetka.com.ua/goods/images/big/288909547.jpg',
        "description": "These are stylish Nike shoes with a sleek design.",
        "content": "The Nike Shoes 01 offer a perfect blend of style and comfort. They are crafted with premium materials and have a durable sole for long-lasting performance.",
        "price": 23,
        "colors": ["red", "black", "crimson", "teal"],
    },
    {
        "id": "2",
        "title": "Nike Shoes 02",
        "image": 'https://content2.rozetka.com.ua/goods/images/big/288909547.jpg',
        "description": "Discover the ultimate comfort with Nike Shoes 02.",
        "content": "These shoes are designed to provide exceptional comfort and support. They feature a breathable upper and a cushioned insole for a plush feel.",
        "price": 1900,
        "colors": ["red", "crimson", "teal"],
    },
    {
        "id": "3",
        "title": "Nike Shoes 03",
        "image": 'https://content2.rozetka.com.ua/goods/images/big/288909547.jpg',
        "description": "Elevate your style with Nike Shoes 03.",
        "content": "The Nike Shoes 03 are perfect for any casual or sporty outfit. They offer excellent traction and stability, making them ideal for everyday wear.",
        "price": 5000,
        "colors": ["lightblue", "white", "crimson", "teal"],
    },
    {
        "id": "4",
        "title": "Nike Shoes 04",
        "image": 'https://content2.rozetka.com.ua/goods/images/big/288909547.jpg',
        "description": "Get ready for adventure with Nike Shoes 04.",
        "content": "The Nike Shoes 04 are designed for outdoor enthusiasts. They feature a rugged construction and a water-resistant upper to keep your feet dry in any weather.",
        "price": 1500,
        "colors": ["orange", "black", "crimson", "teal"],
    },
    {
        "id": "5",
        "title": "Nike Shoes 05",
        "image": 'https://content2.rozetka.com.ua/goods/images/big/288909547.jpg',
        "description": "Experience lightweight comfort with Nike Shoes 05.",
        "content": "These shoes are made with lightweight materials to reduce fatigue during long walks or runs. The Nike Shoes 05 also offer excellent breathability for added comfort.",
        "price": 1000,
        "colors": ["orange", "black", "crimson", "teal"],
        "count": 1
    },
    {
        "id": "6",
        "title": "Nike Shoes 06",
        "image": 'https://content2.rozetka.com.ua/goods/images/big/288909547.jpg',
        "description": "Step up your fashion game with Nike Shoes 06.",
        "content": "The Nike Shoes 06 are the perfect choice for fashion-forward individuals. They feature a trendy design and are available in a variety of stylish colors.",
        "price": 500,
        "colors": ["orange", "black", "crimson", "teal"],
    }
];
